[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
event_manager = "5sgih4PHTwu1sqxK6Lmr8ZjA9WAHMjev1QMLVychFvrB"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/gabriel/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
